version: '3.9'

services:
  api:
    build:
      context: ./api
      target: dev
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app
    env_file: .env.dev

  client:
    build:
      context: ./client
      target: dev
    ports:
      - "80:3000"
    volumes:
      - ./client:/app

  # Not persistenting storage for this demo
  redis:
    image: redis:alpine
